export const TableData = [
    {
      id: "TASK-1234",
      task: "Crear una Rest Api",
      tag: "Programacion",
      status: "Completada",
      priority: "Baja",
      start: "2024-11-23",
      duration: "3 semanas",
    },
    {
      id: "TASK-5678",
      task: "Diseñar Landing Page",
      tag: "Diseño",
      status: "En progreso",
      priority: "Media",
      start: "2024-11-23",
      duration: "2 semanas",
    },
    {
      id: "TASK-9101",
      task: "Crear un Dashboard",
      tag: "Proyecto",
      status: "Pendiente",
      priority: "Alta",
      start: "2024-11-23",
      duration: "4 semanas",
    },
    {
      id: "TASK-1121",
      task: "Clases de Cocina",
      tag: "Cocina",
      status: "En pausa",
      priority: "Baja",
      start: "2024-11-23",
      duration: "2 semanas",
    },
    {
      id: "TASK-3141",
      task: "Proyecto de Desarrollo Web",
      tag: "Trabajo",
      status: "En progreso",
      priority: "Alta",
      start: "2024-07-25",
      duration: "1 mes",
    },
    {
      id: "TASK-5161",
      task: "Entrenamiento de Maratón",
      tag: "Deporte",
      status: "Completada",
      priority: "Media",
      start: "2024-05-01",
      duration: "3 meses",
    },
    {
      id: "TASK-7181",
      task: "Estudio de TypeScript",
      tag: "Programación",
      status: "En progreso",
      priority: "Alta",
      start: "2024-08-15",
      duration: "1 semana",
    },
    {
      id: "TASK-9202",
      task: "Organización de Fiesta",
      tag: "Social",
      status: "Pendiente",
      priority: "Baja",
      start: "2024-12-01",
      duration: "1 día",
    },
    {
      id: "TASK-1223",
      task: "Viaje de Negocios",
      tag: "Trabajo",
      status: "En progreso",
      priority: "Media",
      start: "2024-10-05",
      duration: "3 días",
    },
    {
      id: "TASK-3242",
      task: "Mantenimiento de Jardín",
      tag: "Hogar",
      status: "En pausa",
      priority: "Baja",
      start: "2024-07-30",
      duration: "2 semanas",
    },
    {
      id: "TASK-5262",
      task: "Lectura de Novela",
      tag: "Personal",
      status: "Pendiente",
      priority: "Media",
      start: "2024-09-10",
      duration: "1 semana",
    },
    {
      id: "TASK-7282",
      task: "Curso de Fotografía",
      tag: "Hobby",
      status: "En progreso",
      priority: "Baja",
      start: "2024-08-01",
      duration: "4 semanas",
    },
    {
      id: "TASK-9303",
      task: "Revisión de Código",
      tag: "Trabajo",
      status: "Completada",
      priority: "Alta",
      start: "2024-07-15",
      duration: "3 días",
    },
  ];